import { Component } from "react"

import SectionSMClass        from "./SectionSMClass"
import SectionEnum           from "./SectionEnum"
import SectionGlobalFunction from "./SectionGlobalFunction"
import SectionConstants      from "./SectionConstants"

// ------- jQuery for parsing the existing XML files
// -------    where most of the documentation is
import $ from "jquery"

// ------- highlightjs sot that multiline <code> blocks can
// -------     have syntax coloring
import hljs from "highlight.js"

// ------- custom stylesheet for LuaAPI
import "../_styles/api.css"

import { supportedAPIs, supportedAPIsMap, default_url, getAPIdocURL } from "./modules/SupportedAPIs.js"
import { formatTextWithLinks, getReturnValue } from "./modules/LuaAPIHelpers.js"

class LuaAPI extends Component {

	constructor(props){
		super()

		const urlParams    = new URLSearchParams(window.location.search)
		const engineString = urlParams.get("engine")
		const versionString= urlParams.get("version")

		if (supportedAPIsMap[engineString] && supportedAPIsMap[engineString][versionString]){
			const selected_url = getAPIdocURL(engineString, versionString)
			this.state = { isLoaded: false, yOffset: 0, selectedAPI: { url: selected_url, engineName: engineString, versionName: versionString}}
		} else{
			this.state = { isLoaded: false, yOffset: 0, selectedAPI: { url: default_url,  engineName: supportedAPIs[0].name, versionName: supportedAPIs[0].versions[0].name}}
		}

		// docs will contain documentation data read in from outside files
		// Lua.xml, LuaDocumentation.xml, and FunctionDefinitions.csv
		this.docs = {
			github: {},
		}

		this.sections = [ "Actors", "Screens", "Classes", "Singletons", "Namespaces", "Enums" ]

		// pojos containing just the actor/singleton class names, namespace names, and enum strings as keys
		// used for convenient lookup in getReturnValue() and to pass up to LuaAPISidebar
		for (const i in this.sections){
			this[this.sections[i]] = {}
		}

		// ensure that the following functions have access to "this"
		this.fetchAndParseXML = this.fetchAndParseXML.bind(this)
		this.bubbleDataUp     = this.bubbleDataUp.bind(this)
		this.getReturnValue   = getReturnValue.bind(this)

		// trigger a custom page scroll now
		this.scroll_window_after_hashchange()
	}

	// ---------------------------------------------------------------------

	componentDidUpdate(){

		this.scroll_window_after_hashchange()

		if (this.props.selectedAPIurl !== undefined){
			if (this.state.selectedAPI.url !== this.props.selectedAPIurl){
				const lua_api = this
				this.setState({	selectedAPI: {
					url: this.props.selectedAPIurl,
					engineName:  this.props.selectedAPIengine,
					versionName: this.props.selectedAPIversion,
				}}, () => {
					lua_api.fetchAndParseXML()
				})
			}
		}
	}

  // called once after initial page load
	componentDidMount(){
		this.fetchAndParseXML()
	}

	fetchAndParseXML(){
		// maintain a handle on this class to be used within the functions below
		const lua_api = this


		// --------------------------------
		// reset the visible API doc
		// XXX: make this a reusable function?
		for (const i in this.sections){
			this[this.sections[i]] = {}
		}

		lua_api.setState({
			isLoaded: false,
			G: null,
		})
		// --------------------------------

		// ---------------------------------------------------------------------
		// get documentation files using jQuery
		// then parse them into a usable data structure for this React app

		const url = this.state.selectedAPI.url

		// ------------------------

		// XXX: this when-then-then-then logic is such a mess
		$.when(

			// We have three xml files to retrieve data from:
			//   Lua.xml
			//      a list of classes and functions, autogenerated using the CLI argument
			//      "--ExportLuaInformation" when starting StepMania
			//   LuaDocumentation.xml
			//      corresponding descriptions of classes and functions listed in Lua.xml
			//      this file is manually kept up-to-date by humans
			//   FunctionDefs.json
			//      additional metadata, specific to this Lua-for-SM5 project
			//      autogenerated when the AuxiliaryLuadocData.lua file included with this
			//      project is added to a StepMania theme
			//
			// All classes, methods, functions, etc. should be in Lua.xml, but not everything
			// has a corresponding explanation written by a human in LuaDocumentation.xml

			// ------------------------
			// $.get() returns a string
			// use jquery's .parseXML() to convert that string to an XMLDocument

			$.get(url + "LuaDocumentation.xml", (luadoc) => {
				lua_api.docs.luadoc = $($.parseXML(luadoc)).children()
			}),

			$.get(url + "Lua.xml", (luadotxml) => {
				lua_api.docs.luadotxml = $($.parseXML(luadotxml)).children()
			}),

			$.get(`./Luadoc++/${this.state.selectedAPI.engineName}/${this.state.selectedAPI.versionName}.json`)
				.done((funcdefs) => {
					// XXX: fetching a non-existent json file returns the stringified html content instead of json
					// checking to see if the response is an object or a string is realllllllly hacky
					if (typeof funcdefs == "object"){
						lua_api.docs.github.funcdefs = funcdefs
					} else {
						lua_api.docs.github.funcdefs = {};
					}
				})
				.fail(()=>{
					lua_api.docs.github.funcdefs = {};
				})

		).then(function(){

			const documentation = {
				classes:          lua_api.docs.luadoc.children("Classes"),
				actors:           lua_api.docs.luadoc.children("Actors"),
				screens:          lua_api.docs.luadoc.children("Screens"),
				namespaces:       lua_api.docs.luadoc.children("Namespaces"),
				enums:            lua_api.docs.luadoc.children("Enums"),
				singletons:       lua_api.docs.luadoc.children("Singletons"),
				global_functions: lua_api.docs.luadoc.children("GlobalFunctions"),
				constants:        lua_api.docs.luadoc.children("Constants"),
			}

			const classes          = Array.from(lua_api.docs.luadotxml.children("Classes").children("Class"))
			const namespaces       = Array.from(lua_api.docs.luadotxml.children("Namespaces").children("Namespace"))
			const enums            = Array.from(lua_api.docs.luadotxml.children("Enums").children("Enum"))
			const singletons       = Array.from(lua_api.docs.luadotxml.children("Singletons").children("Singleton"))
			const global_functions = Array.from(lua_api.docs.luadotxml.children("GlobalFunctions").children("Function"))
			const constants        = Array.from(lua_api.docs.luadotxml.children("Constants").children("Constant"))

			// ---------------------------------------------------------------------
			// sort arrays alphabetically; sorting now ensures sequence within sidebar expandables
			// matches sequence in document

			const sortByAttr = function(attr){
			  return function(a, b){
					if ($(a).attr(attr).toUpperCase() < $(b).attr(attr).toUpperCase()){ return -1}
					if ($(a).attr(attr).toUpperCase() > $(b).attr(attr).toUpperCase()){ return 1}
					return 0
				}
			}

			classes.sort(sortByAttr("name"))
			namespaces.sort(sortByAttr("name"))
			enums.sort(sortByAttr("name"))
			singletons.sort(sortByAttr("class"))

			// not sorted for now; these don't have expandable lists in the sidebar
			// TODO: think about how to helpfully organize Global Functions
			// global_functions.sort(sortByAttr("name"))
			// constants.sort(sortByAttr("name"))

			// ---------------------------------------------------------------------
			// first, populate lua_api.Singletons object with the names of each singleton and retain it as state
			singletons.forEach(s => lua_api.Singletons[s.attributes.class.textContent] = s.attributes.name.textContent)
			// also include the SM5 Lua Namespace names
			namespaces.forEach(namespace => lua_api.Namespaces[namespace.attributes[0].nodeValue] = true)
			// and Enums strings, too
			enums.forEach(e => lua_api.Enums[e.attributes.name.textContent] = true)

			// next, do similarly with lua_api.Classes, filling it with the names of
			// each stepmania class.  Note that lua_api.Classes contains info for what
			// this React app presents as "Actors", "Screens", "Other Classes", and Singletons!
			classes.forEach(cls => {
				const class_name = cls.attributes.name.textContent

				// don't add singletons here; those have already been added to lua_api.Singletons
				// just skip to the next classes.forEach iteration
				if (class_name in lua_api.Singletons){ return }

				const class_doc = $(documentation.classes).find("Class[name=" + class_name + "]")
				const grouping  = class_doc.attr("grouping") || "SMClass"
				const mapping = {
					Actor: "Actors",
					Screen: "Screens",
					SMClass: "Classes",
				}

				lua_api[mapping[grouping]][class_name] = true
			})

			lua_api.bubbleDataUp()

			// ---------------------------------------------------------------------

			const G = [
				{ data: [], desc: formatTextWithLinks(documentation.actors.children("Description"),           lua_api) },  // 0: actors
				{ data: [], desc: formatTextWithLinks(documentation.screens.children("Description"),          lua_api) },  // 1: screens
				{ data: [], desc: formatTextWithLinks(documentation.classes.children("Description"),          lua_api) },  // 2: classes
				{ data: [], desc: formatTextWithLinks(documentation.namespaces.children("Description"),       lua_api) },  // 3: namespaces
				{ data: [], desc: formatTextWithLinks(documentation.enums.children("Description"),            lua_api) },  // 4: enums
				{ data: [], desc: formatTextWithLinks(documentation.singletons.children("Description"),       lua_api) },  // 5: singletons
				{ data: [], desc: formatTextWithLinks(documentation.global_functions.children("Description"), lua_api) },  // 6: global_functions
				{ data: [], desc: formatTextWithLinks(documentation.constants.children("Description"),        lua_api) },  // 7: constants
			]

			// ---------------------------------------------------------------------
			// process each actor_class...

			classes.forEach(function(sm_class){

				const class_name = $(sm_class).attr("name")

				// if this class is a singleton, skip to the next forEach iteration
				// so its methods and description don't get put in with actor, screen, or class methods
				if (lua_api.Singletons[class_name]){ return }

				const class_doc = $(documentation.classes).find("Class[name=" + class_name + "]")

				let unsorted_methods = Array.from($(sm_class).find("Function"))

				// ... sorting each actor class's methods alphabetically, in a case-insensitive manner ...
				unsorted_methods.sort(function(a,b){
					// I'm pretty sure all the text I'm sorting here falls within the ASCII range of 32-126
					// otherwise, I might not be able to rely on doing greater-than less-than comparisons like this
					// for discussion, see: https://stackoverflow.com/q/14677060
					if (a.attributes.name.textContent.toUpperCase() < b.attributes.name.textContent.toUpperCase()){ return -1}
					if (a.attributes.name.textContent.toUpperCase() > b.attributes.name.textContent.toUpperCase()){ return 1}
					return 0
				})

				// ... and get just the method data we want (name, return, args, desc, url to GitHub) for each method
				const sorted_methods = unsorted_methods.map(function(method, i){

					const method_name = $(method).attr("name")
					const method_doc  = $(class_doc).find("Function[name=" + method_name + "]")

					return {
						name: method_name,
						return: lua_api.getReturnValue( method_doc.attr("return") ),
						arguments: method_doc.attr("arguments") || "",
						desc: formatTextWithLinks(method_doc, lua_api),
						url: lua_api.docs.github.funcdefs[class_name] && lua_api.docs.github.funcdefs[class_name][method_name]
					}
				})

				const class_grouping = class_doc.attr("grouping") || "SMClass"
				const index = {
					Actor: 0,
					Screen: 1,
					SMClass: 2,
				}

				const group_mapping = {
					Actor: "Actors",
					Screen: "Screens",
					SMClass: "Classes",
				}
				const base = $(sm_class).attr("base")
				let base_grouping = undefined

				if (base !== undefined){
					const base_doc = $(documentation.classes).find("Class[name=" + base + "]")
					base_grouping = group_mapping[(base_doc.attr("grouping") || "SMClass")]
				}

				// push a new object representing this sm_class to the overall data array
				G[index[class_grouping]].data.push({
					name: class_name,
					base: sm_class.attributes.base !== undefined ? {name: base, grouping: base_grouping} : undefined,
					desc: formatTextWithLinks(class_doc.find("Description"), lua_api),
					methods: sorted_methods,
					grouping: group_mapping[class_grouping],
				})
			})

			// ---------------------------------------------------------------------
			// next, process each namespace...
			namespaces.forEach(function(namespace){
				const _name = $(namespace).attr("name")
				const _doc  = $(documentation.namespaces).find("Namespace[name=" + _name + "]")
				const funcs = []

				$(namespace).children("Function").each(function(i,func){
					const fname = $(func).attr("name")
					const fdoc  = $(documentation.namespaces).find("Function[name=" + fname + "]")
					funcs.push({
						name: $(func).attr("name"),
						return: lua_api.getReturnValue( fdoc.attr("return") ),
						arguments: fdoc.attr("arguments") || "",
						desc: formatTextWithLinks(fdoc, lua_api)
					})
				})

				G[3].data.push({
					name: _name,
					methods: funcs,
					desc: formatTextWithLinks(_doc.find("Description"), lua_api),
					grouping: "Namespaces"
				})
			})

			// ---------------------------------------------------------------------
			// next, process each enum...
			enums.forEach(function(e){
				const _name = $(e).attr("name")
				const _doc  = $(documentation.enums).find("Enum[name=" + _name + "]")
				const values = []

				$(e).children("EnumValue").each(function(i, v){
					values.push({
						name: $(v).attr("name"),
						value: $(v).attr("value")
					})
				})

				G[4].data.push({
					name:  _name,
					values: values,
					desc: formatTextWithLinks(_doc.find("Description"), lua_api)
				})
			})

			// ---------------------------------------------------------------------
			// almost done now; process each singleton...
			singletons.forEach(function(s){
				const sm_class = $(s).attr("class")
				const _doc     = $(documentation.classes).find("Class[name=" + sm_class + "]")

				const methods = Array.from(_doc.find("Function")).map(function(method, i){

					const method_name = $(method).attr("name")
					const method_doc  = $(_doc).find("Function[name=" + method_name + "]")

					return {
						name: method_name,
						return: lua_api.getReturnValue( method_doc.attr("return") ),
						arguments: method_doc.attr("arguments") || "",
						desc: formatTextWithLinks(method_doc, lua_api),
						url: lua_api.docs.github.funcdefs[sm_class] && lua_api.docs.github.funcdefs[sm_class][method_name]
					}
				})

				G[5].data.push({
					name: sm_class,
					methods: methods,
					desc: formatTextWithLinks(_doc.find("Description"), lua_api),
					grouping: "Singletons"
				})
			})

			// ---------------------------------------------------------------------
			// almost done! process each global function...
			global_functions.forEach(function(f){
				const _name = $(f).attr("name")
				const _doc  = $(documentation.global_functions).find("Function[name=" + _name + "]")
				const theme = _doc.attr("theme")

				// don't show Global Functions from the Default theme here; most
				// themes will not use it as their base and won't have its functions
				// just skip to the next forEach() iteration
				if (theme === "default"){ return }

				G[6].data.push({
					name: _name,
					return: lua_api.getReturnValue( _doc.attr("return") ),
					arguments: _doc.attr("arguments"),
					desc: formatTextWithLinks(_doc, lua_api),
					theme: _doc.attr("theme") || "",
					url: lua_api.docs.github.funcdefs.GlobalFunctions && lua_api.docs.github.funcdefs.GlobalFunctions[_name],
					grouping: "GlobalFunctions"
				})
			})

			// ---------------------------------------------------------------------
			// finally! process each Lua constant, and we're done
			constants.forEach(function(c){
				G[7].data.push({
					name: $(c).attr("name"),
					value: $(c).attr("value") || ""
				})
			})

			// ---------------------------------------------------------------------
			// we're out of the heavy lifting forEach loop; it's time to setState
			lua_api.setState({
				isLoaded: true,
				G: G,
			}, () => {
				lua_api.bubbleDataUp()
			})

		}).then(function(){
			// this second .then() handler is VERY likely to called after React
			// has already mounted the LuaAPI component
			// so once we are here, trigger a window scroll to ensure the user
			// is the correct section of the document
			lua_api.scroll_window_after_hashchange()

		}).then(()=>{
			// highlightjs
			document.querySelectorAll("pre code").forEach(block => {
				hljs.highlightElement(block);
			})
		})
	}

	bubbleDataUp(){
		this.props.parentCallback({
			actors:     Object.keys(this.Actors),
			screens:    Object.keys(this.Screens),
			sm_classes: Object.keys(this.Classes),
			namespaces: Object.keys(this.Namespaces),
			enums:      Object.keys(this.Enums),
			singletons: Object.keys(this.Singletons),
			isLoaded: this.state.isLoaded,
		})
	}

	updateHash(hash){
		window.location.hash = "#" + hash
	}

	scroll_window_after_hashchange(hash){
		hash = (hash ?? window.location.hash)

		if (hash) {
			// hack: use hyphens in the url hash as a way of measuring "depth"
			// that is, are we on #Screens, #Screens-Screen, or #Screens-Screen-AddInputCallback
			// offset by different amounts to accommodate sticky headers
			const depth = (hash.match(/-/g) || []).length

			hash = hash.replace("#","")
			const el = document.getElementById(hash)
			if (el){
				const y_offset = el.offsetTop
				if (y_offset){
					const topbar_height = depth > 1 ? 108 : 60

					// offset for #GlobalFunctions-[thing] is special-cased for now
					const h3_height = depth > 0 && hash.substring(0, 15)==="GlobalFunctions" ? 40 : 0

					const yOffset = y_offset - topbar_height - h3_height

					// only call setState if the value has changed
					if (this.state.yOffset !== yOffset){
						this.setState({yOffset: yOffset})
						window.scrollTo(0, yOffset)

						// hide #mobileNav if it's open
						if (this.props?.mobile_nav === true) {
							this.props?.hideMobileNav()
						}
					}
				}
			}
		}

		// hide top navbar if it's open
		// XXX: this feels like a kludgy place to do this
		const navbarClasslist = document.getElementById('navbarNav')?.classList
		if (navbarClasslist?.contains('show')){
			navbarClasslist?.remove('show')
		}
	}

	headerUI(){
		let name

		if (this.state.selectedAPI.engineName && this.state.selectedAPI.versionName){
			name = `${this.state.selectedAPI.engineName} ${this.state.selectedAPI.versionName}`
		}

		return (
			<section>
				<h1>{name ?? "SM5"} Lua API</h1>
			</section>
		)
	}

	contentUI(){
    if (this.state === undefined || this.state.isLoaded === false){
			return null
		} else {
			return (
				<section>
					<SectionSMClass        name="Actors"          desc={this.state.G[0].desc} data={this.state.G[0].data} {...this.state} />
					<SectionSMClass        name="Screens"         desc={this.state.G[1].desc} data={this.state.G[1].data} {...this.state} />
					<SectionSMClass        name="Classes"         desc={this.state.G[2].desc} data={this.state.G[2].data} {...this.state} />
					<SectionSMClass        name="Singletons"      desc={this.state.G[5].desc} data={this.state.G[5].data} {...this.state} />
					<SectionSMClass        name="Namespaces"      desc={this.state.G[3].desc} data={this.state.G[3].data} {...this.state} />
					<SectionEnum           name="Enums"           desc={this.state.G[4].desc} data={this.state.G[4].data} />
					<SectionGlobalFunction name="GlobalFunctions" desc={this.state.G[6].desc} data={this.state.G[6].data} {...this.state} />
					<SectionConstants      name="Constants"       desc={this.state.G[7].desc} data={this.state.G[7].data} />
				</section>
			)
		}
	}

	// -----------------------------------------------------------------------------------------

	render() {
		return (
			<div className="LuaAPI ps-md-4">
				{this.headerUI()}
				{this.contentUI()}
			</div>
		)
	}
}

export default LuaAPI;
